image:
  file: .gitpod.dockerfile

tasks:
  - name: iniciar el proyecto
    init: node --version
    #init: npm init -y
  ##- name: instalar dependencias
   ## command: npm install
  #- name: instalar chromedriver
  #  command: npm install chromedriver
  #- name: instalar selenium-webdriver  
    #command: npm install selenium-webdriver chromedriver
  - name: ejecutar prueba 1
    ##command: npm test Scenario1.js
    command: node Scenario1.js
  - name: ejecutar prueba 2
    #command: npm test Scenario2.js
    command: node Scenario2.js
  - name: ejecutar prueba 3
    #command: npm test Scenario3.js
    command: node Scenario3.js
ports:
  - port: 36585
    onOpen: open-browser
  - port: 8080-8090
    onOpen: open-preview