image:
  file: .gitpod.dockerfile

tasks:
  - name: instalar dependencias
    command: npm install

  - name: ejecutar pruebas
    command: npm test

ports:
  - port: 3000
    onOpen: open-browser
  - port: 5000-5005